platform :ios, '8.0'

use_frameworks!
pod 'Alamofire', '~> 3.0'
pod 'Reachability'
pod 'PureLayout'
pod 'ColorUtils'
pod 'libextobjc'
pod 'BlocksKit'
pod 'SDWebImage'
pod 'MBProgressHUD'

target 'MSBPhone' do
    
end